# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/jessie64"
  config.vm.network "private_network", ip: "192.168.50.4"
  config.vm.hostname = "lightning.local"
  config.vm.provision :shell, path: "bootstrap.sh", privileged: true
  config.vm.synced_folder ".", "/vagrant", type: "nfs"
  config.vm.synced_folder "../", "/var/www/demo", type: "nfs"
end
